%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% David Lesaint (david.lesaint@univ-angers.fr)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% INFLUENCE TYPE INCLUSION FILE



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% FILE INCLUSION

%% BOOLEAN
%include "./../itype/type/itype_bool_api.mzn";

%% RATIONAL
include "./../itype/type/itype_rational_api.mzn";

%% INTEGER TODO
% include "./../itype/type/itype_range_api.mzn";

%% ORDER TODO
% include "./../itype/type/itype_order_api.mzn";

%% SYMBOLIC (ENUMERATION)
%  include "./../itype/type/itype_enum_api.mzn";
