%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% David Lesaint (david.lesaint@univ-angers.fr)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% INFLUENCE PROPAGATION OPERATION INCLUSION FILE



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% FILE INCLUSION

% BOOLEAN AND/OR
%include "./../itype/operations/itype_ops_bool.mzn";

%% RATIONAL
%include "./../itype/operations/itype_ops_rational.mzn";

%% INTEGER TODO
% include "./../itype/operations/itype_ops_.mzn";

%% ORDER TODO
% include "./../itype/operations/itype_ops_min_max.mzn";

%% SYMBOLIC I_AND/I_OR
include "./../itype/operations/itype_ops_enum.mzn";

