%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% David Lesaint (david.lesaint@univ-angers.fr)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% INCLUSION FILE FOR CMQL



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% FILE INCLUSION

include "./../cmql/primitive_api.mzn";
include "./../cmql/primitive/primitive_path_value.mzn";
include "./../cmql/primitive/primitive_value.mzn";
include "./../cmql/primitive/primitive_path_value_classic.mzn";
include "./../cmql/primitive/primitive_path.mzn";
include "./../cmql/primitive/primitive_value_classic.mzn";
include "./../cmql/primitive/primitive_length.mzn";
