%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% David Lesaint (david.lesaint@univ-angers.fr)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% INCLUSION FILE FOR CMQL



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% FILE INCLUSION

include "./../cmql/primitive_api.mzn";
include "./../cmql/primitive/K-variable.mzn";
include "./../cmql/primitive/concatenation.mzn";
include "./../cmql/primitive/inclusion.mzn";